app:
  name: HyenaServiceTest

server:
  address: 0.0.0.0
  port: 8089
  use-forward-headers: true
  compression.enabled: true


management:
  context-path: /admin
  security:
    enabled: false



logging:
  level:
    io.github.alphajiang.hyena: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36}.%M\\(%line\\) - %msg%n"

hyena:
  idempotent: redis




spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: hyena
    username: test
    password: 123456
    # connect to host.docker.internal instead of 127.0.0.1 or localhost, in order to connect from docker to mysql on localhost
    url: jdbc:mysql://127.0.0.1:3306/hyena?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowMultiQueries=true
    #url: jdbc:mysql://47.96.253.169:3306/hyena?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowMultiQueries=true
    initialPoolSize: 1
    minPoolSize: 1
    maxPoolSize: 10
    acquireIncrement: 1
    maxIdleTime: 10
    checkoutTimeout: 30000
  redis:
    database: 3
    host: localhost # run from docker, use redis not localhost to refer to the redis-instance inside docker container
    port: 6379
    password:
    timeout: 4000
    ssl: false
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 10000
      min-idle: 0
  ubt:
    #networkPrefix: http://47.96.253.169:8545/
    #contractAddress: '0x819a40566475672E4395bF4dF274C420ABfeb6E1'
    #primaryAcctAddress: '0xa83B181067f77C787b748DF16F1338C23E20fFAB'
    #primaryAcctpriKey: 0c28bc97f7670691e9e5cca7142e40f10131ba463e790dd4e6fe6eb871efe8b2
    networkPrefix: http://localhost:8545/
    contractAddress: '0x16247c2cCb17124247DA0bc2631de1330947ca4a'
    primaryAcctAddress: '0x79C15610db6Bb73f79195b6C2C87649622916776'
    primaryAcctpriKey: aed3e51be7eef5c2bdb5efa24d2fce030c060dc229cf20e511bb5f861c9358c6