version: '3'

services:
  appplication:
    image: ubt:3.0
    ports:
      - "8089:8089"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    links:
      - redis
    networks:
      - backend
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"